server:
  port: 8081
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://nafsicdepvurqw:78546071502001ba1c18086b93043c2096b6f0720e28c0918206685e42a93286@ec2-52-213-167-210.eu-west-1.compute.amazonaws.com:5432/d4hjl9jm7k68vq
    username: nafsicdepvurqw
    password: 78546071502001ba1c18086b93043c2096b6f0720e28c0918206685e42a93286
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Project created for the Santander Java-Angular Bootcamp - Backend.
